import type { Topic } from "./types";

export interface Feed {
  name: string;
  url: string;
}

const CONFLICT_FEEDS: readonly Feed[] = [
  { name: "BBC News",          url: "https://feeds.bbci.co.uk/news/world/rss.xml" },
  { name: "Al Jazeera",        url: "https://www.aljazeera.com/xml/rss/all.xml" },
  { name: "The Guardian",      url: "https://www.theguardian.com/world/rss" },
  { name: "France 24",         url: "https://www.france24.com/en/rss" },
  { name: "DW",                url: "https://rss.dw.com/xml/rss-en-world" },
  { name: "NYT World",         url: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml" },
  { name: "NPR News",          url: "https://feeds.npr.org/1001/rss.xml" },
  { name: "ABC News",          url: "https://abcnews.go.com/abcnews/internationalheadlines" },
  { name: "Times of Israel",   url: "https://www.timesofisrael.com/feed/" },
  { name: "Jerusalem Post",    url: "https://www.jpost.com/rss/rssfeedsfrontpage.aspx" },
  { name: "Middle East Eye",   url: "https://www.middleeasteye.net/rss" },
  { name: "War on the Rocks",  url: "https://warontherocks.com/feed/" },
  { name: "The War Zone",      url: "https://www.thedrive.com/the-war-zone/rss" },
  { name: "Google News Iran",  url: "https://news.google.com/rss/search?q=iran+israel+usa+conflict&hl=en" },
  { name: "Sky News",          url: "https://feeds.skynews.com/feeds/rss/world.xml" },
  { name: "CBS News",          url: "https://www.cbsnews.com/latest/rss/world" },
  { name: "Euronews",          url: "https://www.euronews.com/rss?level=theme&name=news" },
  { name: "The Hill",          url: "https://thehill.com/feed/" },
  { name: "Politico Defense",  url: "https://rss.politico.com/defense.xml" },
  { name: "CNBC World",        url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100727362" },
];

const AI_FEEDS: readonly Feed[] = [
  { name: "TechCrunch AI",     url: "https://techcrunch.com/category/artificial-intelligence/feed/" },
  { name: "The Verge AI",      url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml" },
  { name: "Wired AI",          url: "https://www.wired.com/feed/tag/ai/latest/rss" },
  { name: "Ars Technica",      url: "https://feeds.arstechnica.com/arstechnica/technology-lab" },
  { name: "VentureBeat AI",    url: "https://venturebeat.com/category/ai/feed/" },
  { name: "MIT Tech Review",   url: "https://www.technologyreview.com/feed/" },
  { name: "The Register AI",   url: "https://www.theregister.com/software/ai_ml/headlines.atom" },
  { name: "AI News",           url: "https://www.artificialintelligence-news.com/feed/" },
  { name: "Google AI Blog",    url: "https://blog.google/technology/ai/rss/" },
  { name: "OpenAI Blog",       url: "https://openai.com/blog/rss.xml" },
  { name: "Hacker News AI",    url: "https://hnrss.org/newest?q=AI+OR+LLM+OR+cursor+OR+copilot+OR+claude" },
  { name: "Hugging Face Blog", url: "https://huggingface.co/blog/feed.xml" },
  { name: "Towards Data Sci.", url: "https://towardsdatascience.com/feed" },
  { name: "DeepMind Blog",     url: "https://deepmind.google/blog/rss.xml" },
  { name: "Simon Willison",    url: "https://simonwillison.net/atom/everything/" },
  { name: "Engadget",          url: "https://www.engadget.com/rss.xml" },
  { name: "Marktechpost",      url: "https://www.marktechpost.com/feed/" },
  { name: "The Decoder",       url: "https://the-decoder.com/feed/" },
  { name: "ZDNET AI",          url: "https://www.zdnet.com/topic/artificial-intelligence/rss.xml" },
  { name: "Last Week in AI",   url: "https://lastweekin.ai/feed" },
];

const CRYPTO_FEEDS: readonly Feed[] = [
  { name: "CoinDesk",          url: "https://www.coindesk.com/arc/outboundfeeds/rss/" },
  { name: "Cointelegraph",     url: "https://cointelegraph.com/rss" },
  { name: "The Block",         url: "https://www.theblock.co/rss.xml" },
  { name: "Decrypt",           url: "https://decrypt.co/feed" },
  { name: "NewsBTC",           url: "https://www.newsbtc.com/feed/" },
  { name: "U.Today",           url: "https://u.today/rss" },
  { name: "Bitcoinist",        url: "https://bitcoinist.com/feed/" },
  { name: "The Daily Hodl",    url: "https://dailyhodl.com/feed/" },
  { name: "CryptoPotato",      url: "https://cryptopotato.com/feed/" },
  { name: "Bitcoin Magazine",   url: "https://bitcoinmagazine.com/feed" },
  { name: "Bitcoin News",      url: "https://news.bitcoin.com/feed/" },
  { name: "Blockworks",        url: "https://blockworks.co/feed" },
  { name: "Glassnode Insights", url: "https://insights.glassnode.com/rss/" },
  { name: "BitcoinDev Blog",   url: "https://blog.lopp.net/rss/" },
  { name: "Stacker News",      url: "https://stacker.news/rss" },
  { name: "Crypto Briefing",   url: "https://cryptobriefing.com/feed/" },
  { name: "AMBCrypto",         url: "https://ambcrypto.com/feed/" },
  { name: "Blockonomi",        url: "https://blockonomi.com/feed/" },
  { name: "Coingape",          url: "https://coingape.com/feed/" },
  { name: "Crypto News",       url: "https://cryptonews.com/news/feed/" },
];

const ROBOTICS_FEEDS: readonly Feed[] = [
  { name: "The Robot Report",       url: "https://www.therobotreport.com/feed/" },
  { name: "TechCrunch Robotics",    url: "https://techcrunch.com/category/robotics/feed/" },
  { name: "The Verge AI",           url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml" },
  { name: "Ars Technica",           url: "https://feeds.arstechnica.com/arstechnica/technology-lab" },
  { name: "Wired AI",               url: "https://www.wired.com/feed/tag/ai/latest/rss" },
  { name: "VentureBeat AI",         url: "https://venturebeat.com/category/ai/feed/" },
  { name: "MIT Tech Review",        url: "https://www.technologyreview.com/feed/" },
  { name: "Hacker News Robotics",   url: "https://hnrss.org/newest?q=Unitree+OR+Optimus+OR+humanoid+robot+OR+Figure+AI+OR+Boston+Dynamics" },
  { name: "Robohub",                url: "https://robohub.org/feed/" },
  { name: "Singularity Hub",        url: "https://singularityhub.com/feed/" },
  { name: "Google DeepMind",        url: "https://deepmind.google/blog/rss.xml" },
  { name: "OpenAI Blog",            url: "https://openai.com/blog/rss.xml" },
  { name: "Futurism",               url: "https://futurism.com/feed" },
  { name: "Slash Gear",             url: "https://www.slashgear.com/feed" },
  { name: "IEEE Robotics",          url: "https://spectrum.ieee.org/feeds/topic/robotics.rss" },
  { name: "Hackaday",               url: "https://hackaday.com/blog/feed/" },
  { name: "Science Daily Robots",   url: "https://www.sciencedaily.com/rss/computers_math/robotics.xml" },
  { name: "Engadget",               url: "https://www.engadget.com/rss.xml" },
  { name: "ZDNET Robotics",         url: "https://www.zdnet.com/topic/robotics/rss.xml" },
  { name: "SCMP Tech",              url: "https://www.scmp.com/rss/5/feed" },
];

const BITCOIN_FEEDS: readonly Feed[] = [
  { name: "Bitcoin Magazine",          url: "https://bitcoinmagazine.com/.rss/full/" },
  { name: "CoinDesk",                  url: "https://www.coindesk.com/arc/outboundfeeds/rss/?outputType=xml" },
  { name: "Cointelegraph Bitcoin",     url: "https://cointelegraph.com/rss/tag/bitcoin" },
  { name: "NewsBTC",                   url: "https://www.newsbtc.com/feed/" },
  { name: "Bitcoinist",                url: "https://bitcoinist.com/feed/" },
  { name: "Bitcoin.com News",          url: "https://news.bitcoin.com/feed/" },
  { name: "Decrypt",                   url: "https://decrypt.co/feed" },
  { name: "The Bitcoin Layer",         url: "https://thebitcoinlayer.substack.com/feed" },
  { name: "CryptoNews Bitcoin",        url: "https://cryptonews.com/news/bitcoin-news/feed/" },
  { name: "Blockworks",                url: "https://blockworks.co/feed" },
  { name: "The Block",                 url: "https://www.theblock.co/rss.xml" },
  { name: "AMBCrypto",                 url: "https://ambcrypto.com/feed/" },
  { name: "WatcherGuru",               url: "https://watcher.guru/news/feed" },
  { name: "CryptoPotato",              url: "https://cryptopotato.com/feed/" },
  { name: "Coingape",                  url: "https://coingape.com/feed/" },
  { name: "Bitcoin Insider",           url: "https://www.bitcoininsider.org/rss.xml" },
  { name: "Protos",                    url: "https://protos.com/feed/" },
  { name: "Unchained",                 url: "https://unchainedcrypto.com/feed/" },
  { name: "Coinpedia",                 url: "https://coinpedia.org/feed/" },
  { name: "Crypto Briefing",           url: "https://cryptobriefing.com/feed/" },
];

const VIDEOGAMES_FEEDS: readonly Feed[] = [
  { name: "IGN",                    url: "https://feeds.feedburner.com/ign/all" },
  { name: "Kotaku",                 url: "https://kotaku.com/rss" },
  { name: "GameSpot",               url: "https://www.gamespot.com/feeds/mashup/" },
  { name: "PC Gamer",               url: "https://www.pcgamer.com/rss/" },
  { name: "Eurogamer",              url: "https://www.eurogamer.net/feed" },
  { name: "Polygon",                url: "https://www.polygon.com/rss/index.xml" },
  { name: "Rock Paper Shotgun",     url: "https://www.rockpapershotgun.com/feed" },
  { name: "VG247",                  url: "https://www.vg247.com/feed" },
  { name: "GamesRadar+",            url: "https://www.gamesradar.com/rss/" },
  { name: "Destructoid",            url: "https://www.destructoid.com/feed/" },
  { name: "Nintendo Life",          url: "https://www.nintendolife.com/feeds/latest" },
  { name: "Push Square",            url: "https://www.pushsquare.com/feeds/latest" },
  { name: "Pure Xbox",              url: "https://www.purexbox.com/feeds/latest" },
  { name: "The Verge Gaming",       url: "https://www.theverge.com/rss/games/index.xml" },
  { name: "Ars Technica Gaming",    url: "https://feeds.arstechnica.com/arstechnica/gaming" },
  { name: "GamesIndustry.biz",      url: "https://www.gamesindustry.biz/feed" },
  { name: "Siliconera",             url: "https://www.siliconera.com/feed/" },
  { name: "Dualshockers",           url: "https://www.dualshockers.com/feed/" },
  { name: "Wired Gaming",           url: "https://www.wired.com/feed/tag/game-reviews/latest/rss" },
  { name: "PCGamesN",               url: "https://www.pcgamesn.com/mainrss.xml" },
];

const AI_ENGINEERING_FEEDS: readonly Feed[] = [
  { name: "Latent Space",            url: "https://www.latent.space/feed" },
  { name: "Simon Willison",          url: "https://simonwillison.net/atom/everything/" },
  { name: "Eugene Yan",              url: "https://eugeneyan.com/rss/" },
  { name: "Chip Huyen",              url: "https://huyenchip.com/feed.xml" },
  { name: "LangChain Blog",          url: "https://blog.langchain.dev/rss/" },
  { name: "Hugging Face Blog",       url: "https://huggingface.co/blog/feed.xml" },
  { name: "GitHub Blog",             url: "https://github.blog/feed/" },
  { name: "OpenAI Blog",             url: "https://openai.com/blog/rss.xml" },
  { name: "Google AI Blog",          url: "https://blog.google/technology/ai/rss/" },
  { name: "Vercel Blog",             url: "https://vercel.com/atom" },
  { name: "The Verge AI",            url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml" },
  { name: "TechCrunch AI",           url: "https://techcrunch.com/category/artificial-intelligence/feed/" },
  { name: "VentureBeat AI",          url: "https://venturebeat.com/category/ai/feed/" },
  { name: "DeepMind Blog",           url: "https://deepmind.google/blog/rss.xml" },
  { name: "Together AI Blog",        url: "https://www.together.ai/blog/rss.xml" },
  { name: "Replicate Blog",          url: "https://replicate.com/blog/rss" },
  { name: "W&B Fully Connected",     url: "https://wandb.ai/fully-connected/rss.xml" },
  { name: "The Pragmatic Engineer",  url: "https://newsletter.pragmaticengineer.com/feed" },
  { name: "InfoQ AI/ML",             url: "https://feed.infoq.com/ai-ml-data-eng/" },
  { name: "MIT Tech Review AI",      url: "https://www.technologyreview.com/topic/artificial-intelligence/feed" },
];

const ELON_FEEDS: readonly Feed[] = [
  { name: "Google News Elon",      url: "https://news.google.com/rss/search?q=elon+musk&hl=en" },
  { name: "TechCrunch",            url: "https://techcrunch.com/feed/" },
  { name: "The Verge",             url: "https://www.theverge.com/rss/index.xml" },
  { name: "Ars Technica",          url: "https://feeds.arstechnica.com/arstechnica/technology-lab" },
  { name: "Wired",                 url: "https://www.wired.com/feed/rss" },
  { name: "Engadget",              url: "https://www.engadget.com/rss.xml" },
  { name: "CNBC Tech",             url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=19854910" },
  { name: "Reuters Tech",          url: "https://www.reutersagency.com/feed/?taxonomy=best-topics&post_type=best" },
  { name: "Bloomberg Tech",        url: "https://feeds.bloomberg.com/technology/news.rss" },
  { name: "Electrek",              url: "https://electrek.co/feed/" },
  { name: "Teslarati",             url: "https://www.teslarati.com/feed/" },
  { name: "InsideEVs",             url: "https://insideevs.com/rss/make/tesla/" },
  { name: "SpaceNews",             url: "https://spacenews.com/feed/" },
  { name: "NASASpaceflight",       url: "https://www.nasaspaceflight.com/feed/" },
  { name: "The Guardian Tech",     url: "https://www.theguardian.com/technology/rss" },
  { name: "Business Insider Tech",  url: "https://www.businessinsider.com/tech?IR=T&format=rss" },
  { name: "Forbes Innovation",     url: "https://www.forbes.com/innovation/feed/" },
  { name: "Futurism",              url: "https://futurism.com/feed" },
  { name: "VentureBeat",           url: "https://venturebeat.com/feed/" },
  { name: "ZDNET",                 url: "https://www.zdnet.com/news/rss.xml" },
];

const FEEDS_BY_TOPIC: Record<Topic, readonly Feed[]> = {
  conflict: CONFLICT_FEEDS,
  ai: AI_FEEDS,
  crypto: CRYPTO_FEEDS,
  robotics: ROBOTICS_FEEDS,
  bitcoin: BITCOIN_FEEDS,
  videogames: VIDEOGAMES_FEEDS,
  aiengineering: AI_ENGINEERING_FEEDS,
  elon: ELON_FEEDS,
};

export function getFeedsForTopic(topic: Topic): readonly Feed[] {
  return FEEDS_BY_TOPIC[topic];
}
