[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"

[functions."cron-fetching"]
schedule = "* * * * *"

[functions."cron-scoring"]
schedule = "* * * * *"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://8news.netlify.app/*"
  to = "https://8news.ai/:splat"
  status = 301
  force = true
