-- Migration 001: Create topics and feeds tables
-- Run this in Supabase SQL Editor

-- ── 1. Create topics table ──────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS topics (
  id              text PRIMARY KEY,
  label_en        text NOT NULL,
  label_fr        text NOT NULL,
  scoring_domain  text NOT NULL,
  scoring_tier1   text NOT NULL,
  scoring_tier2   text NOT NULL,
  scoring_tier3   text NOT NULL,
  scoring_tier4   text NOT NULL,
  scoring_tier5   text NOT NULL,
  is_active       boolean NOT NULL DEFAULT true,
  sort_order      integer NOT NULL DEFAULT 0,
  last_fetched_at timestamptz,
  last_scored_at  timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS topics_active_idx ON topics (is_active, sort_order);

-- ── 2. Create feeds table ───────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS feeds (
  id         serial PRIMARY KEY,
  topic_id   text NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
  name       text NOT NULL,
  url        text NOT NULL,
  is_active  boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(topic_id, url)
);

CREATE INDEX IF NOT EXISTS feeds_topic_active_idx ON feeds (topic_id, is_active);

-- ── 3. Seed topics ─────────────────────────────────────────────────────

INSERT INTO topics (id, label_en, label_fr, scoring_domain, scoring_tier1, scoring_tier2, scoring_tier3, scoring_tier4, scoring_tier5, sort_order) VALUES
  ('conflict', 'Iran War', 'Iran War',
   'Iran/USA/Israel conflict and Middle East geopolitics',
   'Major strike, peace treaty, new state intervention, UN resolution, casualty report >100',
   'Significant military operation, major sanctions, official leader statement with policy impact',
   'Diplomatic development, troop movement, sourced geopolitical analysis with data',
   'Commentary or opinion without new facts, recycled historical context',
   'Off-topic or no direct link to Iran/USA/Israel conflict',
   0),
  ('ai', 'AI', 'IA',
   'artificial intelligence industry and research',
   'New major model (GPT-5, Gemini 3, Claude 5), benchmark record, acquisition >1B$, historic regulation',
   'Significant release, notable partnership, published research result, funding >100M$',
   'Product update, expert opinion, trend analysis with data',
   'Tutorial, promotional article, speculation without source',
   'Off-topic AI or recycled known information',
   1),
  ('aiengineering', 'AI Eng.', 'AI Eng.',
   'AI engineering, MLOps, LLM infrastructure, and production AI systems',
   'Detailed large-scale technical architecture, major postmortem, transformative new tool (framework, runtime)',
   'In-depth technical guide with benchmarks, production experience report, new AI infra tool release',
   'Interesting technical article without new data, tool comparison',
   'Beginner tutorial, consumer product news, hype without technical substance',
   'Non-technical content, generic AI news without engineering angle',
   2),
  ('robotics', 'Robotics', 'Robotique',
   'robotics, humanoid robots, and AI-powered physical systems',
   'New flagship robot with published specs, massive industrial deployment, major acquisition',
   'Significant technical demo, funding >50M$, industry partnership, new DOF/payload record',
   'Product update, conference coverage, demo video without new specs',
   'Speculation, popularization article without new facts',
   'Off-topic robotics',
   3),
  ('crypto', 'Crypto', 'Crypto',
   'cryptocurrency, blockchain, and DeFi markets',
   'Major regulation (ETF approved/rejected, ban, law), hack >100M$, BTC ±10% in 24h',
   'Significant market movement, institutional partnership, major new DeFi protocol',
   'On-chain analysis, protocol update, notable fund movement',
   'Price prediction, opinion, shitcoin news',
   'Spam, promotional, off-topic crypto',
   4),
  ('bitcoin', 'Bitcoin', 'Bitcoin',
   'Bitcoin exclusively (BTC price, ETFs, mining, Lightning, on-chain, institutional adoption)',
   'New ATH, major ETF approved, halving event, nation-state adoption',
   'Price movement >5%, significant Lightning development, major institution buying',
   'Sourced on-chain analysis, technical update (Core, Ordinals), mining news with data',
   'Price prediction without data, opinion, altcoin mentioned as main topic',
   'Off-topic BTC, altcoin article, spam',
   5),
  ('videogames', 'Video Games', 'Jeux Vidéo',
   'video games industry, releases, studios, and esports',
   'Major AAA announcement, highly anticipated title release, studio acquisition >1B$, Metacritic score for major game',
   'Trailer/gameplay reveal, significant sales results, notable studio closure',
   'Game update, credible sourced rumor, major esport event',
   'Unsourced rumor, ''top 10'' list, promotional content',
   'Off-topic gaming, merchandise, celebrity playing',
   6),
  ('elon', 'Elon Musk', 'Elon Musk',
   'Elon Musk and his companies (Tesla, SpaceX, xAI, X/Twitter, Neuralink, The Boring Company, Starlink)',
   'Major product launch, IPO/valuation milestone, government contract >1B$, breakthrough demo, CEO-level decision with global impact',
   'Significant earnings report, major partnership, regulatory ruling, Starship test, Tesla delivery numbers, xAI model release',
   'Product update, sourced interview, executive appointment, factory milestone, credible sourced report',
   'Elon tweet commentary, opinion piece, speculation without source, personal life gossip',
   'Off-topic or no direct link to Elon Musk or his companies',
   7)
ON CONFLICT (id) DO NOTHING;

-- ── 4. Seed feeds ──────────────────────────────────────────────────────

INSERT INTO feeds (topic_id, name, url) VALUES
  -- conflict (20 feeds)
  ('conflict', 'BBC News', 'https://feeds.bbci.co.uk/news/world/rss.xml'),
  ('conflict', 'Al Jazeera', 'https://www.aljazeera.com/xml/rss/all.xml'),
  ('conflict', 'The Guardian', 'https://www.theguardian.com/world/rss'),
  ('conflict', 'France 24', 'https://www.france24.com/en/rss'),
  ('conflict', 'DW', 'https://rss.dw.com/xml/rss-en-world'),
  ('conflict', 'NYT World', 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml'),
  ('conflict', 'NPR News', 'https://feeds.npr.org/1001/rss.xml'),
  ('conflict', 'ABC News', 'https://abcnews.go.com/abcnews/internationalheadlines'),
  ('conflict', 'Times of Israel', 'https://www.timesofisrael.com/feed/'),
  ('conflict', 'Jerusalem Post', 'https://www.jpost.com/rss/rssfeedsfrontpage.aspx'),
  ('conflict', 'Middle East Eye', 'https://www.middleeasteye.net/rss'),
  ('conflict', 'War on the Rocks', 'https://warontherocks.com/feed/'),
  ('conflict', 'The War Zone', 'https://www.thedrive.com/the-war-zone/rss'),
  ('conflict', 'Google News Iran', 'https://news.google.com/rss/search?q=iran+israel+usa+conflict&hl=en'),
  ('conflict', 'Sky News', 'https://feeds.skynews.com/feeds/rss/world.xml'),
  ('conflict', 'CBS News', 'https://www.cbsnews.com/latest/rss/world'),
  ('conflict', 'Euronews', 'https://www.euronews.com/rss?level=theme&name=news'),
  ('conflict', 'The Hill', 'https://thehill.com/feed/'),
  ('conflict', 'Politico Defense', 'https://rss.politico.com/defense.xml'),
  ('conflict', 'CNBC World', 'https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100727362'),
  -- ai (20 feeds)
  ('ai', 'TechCrunch AI', 'https://techcrunch.com/category/artificial-intelligence/feed/'),
  ('ai', 'The Verge AI', 'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml'),
  ('ai', 'Wired AI', 'https://www.wired.com/feed/tag/ai/latest/rss'),
  ('ai', 'Ars Technica', 'https://feeds.arstechnica.com/arstechnica/technology-lab'),
  ('ai', 'VentureBeat AI', 'https://venturebeat.com/category/ai/feed/'),
  ('ai', 'MIT Tech Review', 'https://www.technologyreview.com/feed/'),
  ('ai', 'The Register AI', 'https://www.theregister.com/software/ai_ml/headlines.atom'),
  ('ai', 'AI News', 'https://www.artificialintelligence-news.com/feed/'),
  ('ai', 'Google AI Blog', 'https://blog.google/technology/ai/rss/'),
  ('ai', 'OpenAI Blog', 'https://openai.com/blog/rss.xml'),
  ('ai', 'Hacker News AI', 'https://hnrss.org/newest?q=AI+OR+LLM+OR+cursor+OR+copilot+OR+claude'),
  ('ai', 'Hugging Face Blog', 'https://huggingface.co/blog/feed.xml'),
  ('ai', 'Towards Data Sci.', 'https://towardsdatascience.com/feed'),
  ('ai', 'DeepMind Blog', 'https://deepmind.google/blog/rss.xml'),
  ('ai', 'Simon Willison', 'https://simonwillison.net/atom/everything/'),
  ('ai', 'Engadget', 'https://www.engadget.com/rss.xml'),
  ('ai', 'Marktechpost', 'https://www.marktechpost.com/feed/'),
  ('ai', 'The Decoder', 'https://the-decoder.com/feed/'),
  ('ai', 'ZDNET AI', 'https://www.zdnet.com/topic/artificial-intelligence/rss.xml'),
  ('ai', 'Last Week in AI', 'https://lastweekin.ai/feed'),
  -- crypto (20 feeds)
  ('crypto', 'CoinDesk', 'https://www.coindesk.com/arc/outboundfeeds/rss/'),
  ('crypto', 'Cointelegraph', 'https://cointelegraph.com/rss'),
  ('crypto', 'The Block', 'https://www.theblock.co/rss.xml'),
  ('crypto', 'Decrypt', 'https://decrypt.co/feed'),
  ('crypto', 'NewsBTC', 'https://www.newsbtc.com/feed/'),
  ('crypto', 'U.Today', 'https://u.today/rss'),
  ('crypto', 'Bitcoinist', 'https://bitcoinist.com/feed/'),
  ('crypto', 'The Daily Hodl', 'https://dailyhodl.com/feed/'),
  ('crypto', 'CryptoPotato', 'https://cryptopotato.com/feed/'),
  ('crypto', 'Bitcoin Magazine', 'https://bitcoinmagazine.com/feed'),
  ('crypto', 'Bitcoin News', 'https://news.bitcoin.com/feed/'),
  ('crypto', 'Blockworks', 'https://blockworks.co/feed'),
  ('crypto', 'Glassnode Insights', 'https://insights.glassnode.com/rss/'),
  ('crypto', 'BitcoinDev Blog', 'https://blog.lopp.net/rss/'),
  ('crypto', 'Stacker News', 'https://stacker.news/rss'),
  ('crypto', 'Crypto Briefing', 'https://cryptobriefing.com/feed/'),
  ('crypto', 'AMBCrypto', 'https://ambcrypto.com/feed/'),
  ('crypto', 'Blockonomi', 'https://blockonomi.com/feed/'),
  ('crypto', 'Coingape', 'https://coingape.com/feed/'),
  ('crypto', 'Crypto News', 'https://cryptonews.com/news/feed/'),
  -- robotics (19 feeds)
  ('robotics', 'The Robot Report', 'https://www.therobotreport.com/feed/'),
  ('robotics', 'TechCrunch Robotics', 'https://techcrunch.com/category/robotics/feed/'),
  ('robotics', 'The Verge AI', 'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml'),
  ('robotics', 'Ars Technica', 'https://feeds.arstechnica.com/arstechnica/technology-lab'),
  ('robotics', 'Wired AI', 'https://www.wired.com/feed/tag/ai/latest/rss'),
  ('robotics', 'VentureBeat AI', 'https://venturebeat.com/category/ai/feed/'),
  ('robotics', 'MIT Tech Review', 'https://www.technologyreview.com/feed/'),
  ('robotics', 'Hacker News Robotics', 'https://hnrss.org/newest?q=Unitree+OR+Optimus+OR+humanoid+robot+OR+Figure+AI+OR+Boston+Dynamics'),
  ('robotics', 'Robohub', 'https://robohub.org/feed/'),
  ('robotics', 'Singularity Hub', 'https://singularityhub.com/feed/'),
  ('robotics', 'Google DeepMind', 'https://deepmind.google/blog/rss.xml'),
  ('robotics', 'OpenAI Blog', 'https://openai.com/blog/rss.xml'),
  ('robotics', 'Futurism', 'https://futurism.com/feed'),
  ('robotics', 'Slash Gear', 'https://www.slashgear.com/feed'),
  ('robotics', 'IEEE Robotics', 'https://spectrum.ieee.org/feeds/topic/robotics.rss'),
  ('robotics', 'Hackaday', 'https://hackaday.com/blog/feed/'),
  ('robotics', 'Science Daily Robots', 'https://www.sciencedaily.com/rss/computers_math/robotics.xml'),
  ('robotics', 'Engadget', 'https://www.engadget.com/rss.xml'),
  ('robotics', 'ZDNET Robotics', 'https://www.zdnet.com/topic/robotics/rss.xml'),
  ('robotics', 'SCMP Tech', 'https://www.scmp.com/rss/5/feed'),
  -- bitcoin (20 feeds)
  ('bitcoin', 'Bitcoin Magazine', 'https://bitcoinmagazine.com/.rss/full/'),
  ('bitcoin', 'CoinDesk', 'https://www.coindesk.com/arc/outboundfeeds/rss/?outputType=xml'),
  ('bitcoin', 'Cointelegraph Bitcoin', 'https://cointelegraph.com/rss/tag/bitcoin'),
  ('bitcoin', 'NewsBTC', 'https://www.newsbtc.com/feed/'),
  ('bitcoin', 'Bitcoinist', 'https://bitcoinist.com/feed/'),
  ('bitcoin', 'Bitcoin.com News', 'https://news.bitcoin.com/feed/'),
  ('bitcoin', 'Decrypt', 'https://decrypt.co/feed'),
  ('bitcoin', 'The Bitcoin Layer', 'https://thebitcoinlayer.substack.com/feed'),
  ('bitcoin', 'CryptoNews Bitcoin', 'https://cryptonews.com/news/bitcoin-news/feed/'),
  ('bitcoin', 'Blockworks', 'https://blockworks.co/feed'),
  ('bitcoin', 'The Block', 'https://www.theblock.co/rss.xml'),
  ('bitcoin', 'AMBCrypto', 'https://ambcrypto.com/feed/'),
  ('bitcoin', 'WatcherGuru', 'https://watcher.guru/news/feed'),
  ('bitcoin', 'CryptoPotato', 'https://cryptopotato.com/feed/'),
  ('bitcoin', 'Coingape', 'https://coingape.com/feed/'),
  ('bitcoin', 'Bitcoin Insider', 'https://www.bitcoininsider.org/rss.xml'),
  ('bitcoin', 'Protos', 'https://protos.com/feed/'),
  ('bitcoin', 'Unchained', 'https://unchainedcrypto.com/feed/'),
  ('bitcoin', 'Coinpedia', 'https://coinpedia.org/feed/'),
  ('bitcoin', 'Crypto Briefing', 'https://cryptobriefing.com/feed/'),
  -- videogames (20 feeds)
  ('videogames', 'IGN', 'https://feeds.feedburner.com/ign/all'),
  ('videogames', 'Kotaku', 'https://kotaku.com/rss'),
  ('videogames', 'GameSpot', 'https://www.gamespot.com/feeds/mashup/'),
  ('videogames', 'PC Gamer', 'https://www.pcgamer.com/rss/'),
  ('videogames', 'Eurogamer', 'https://www.eurogamer.net/feed'),
  ('videogames', 'Polygon', 'https://www.polygon.com/rss/index.xml'),
  ('videogames', 'Rock Paper Shotgun', 'https://www.rockpapershotgun.com/feed'),
  ('videogames', 'VG247', 'https://www.vg247.com/feed'),
  ('videogames', 'GamesRadar+', 'https://www.gamesradar.com/rss/'),
  ('videogames', 'Destructoid', 'https://www.destructoid.com/feed/'),
  ('videogames', 'Nintendo Life', 'https://www.nintendolife.com/feeds/latest'),
  ('videogames', 'Push Square', 'https://www.pushsquare.com/feeds/latest'),
  ('videogames', 'Pure Xbox', 'https://www.purexbox.com/feeds/latest'),
  ('videogames', 'The Verge Gaming', 'https://www.theverge.com/rss/games/index.xml'),
  ('videogames', 'Ars Technica Gaming', 'https://feeds.arstechnica.com/arstechnica/gaming'),
  ('videogames', 'GamesIndustry.biz', 'https://www.gamesindustry.biz/feed'),
  ('videogames', 'Siliconera', 'https://www.siliconera.com/feed/'),
  ('videogames', 'Dualshockers', 'https://www.dualshockers.com/feed/'),
  ('videogames', 'Wired Gaming', 'https://www.wired.com/feed/tag/game-reviews/latest/rss'),
  ('videogames', 'PCGamesN', 'https://www.pcgamesn.com/mainrss.xml'),
  -- aiengineering (20 feeds)
  ('aiengineering', 'Latent Space', 'https://www.latent.space/feed'),
  ('aiengineering', 'Simon Willison', 'https://simonwillison.net/atom/everything/'),
  ('aiengineering', 'Eugene Yan', 'https://eugeneyan.com/rss/'),
  ('aiengineering', 'Chip Huyen', 'https://huyenchip.com/feed.xml'),
  ('aiengineering', 'LangChain Blog', 'https://blog.langchain.dev/rss/'),
  ('aiengineering', 'Hugging Face Blog', 'https://huggingface.co/blog/feed.xml'),
  ('aiengineering', 'GitHub Blog', 'https://github.blog/feed/'),
  ('aiengineering', 'OpenAI Blog', 'https://openai.com/blog/rss.xml'),
  ('aiengineering', 'Google AI Blog', 'https://blog.google/technology/ai/rss/'),
  ('aiengineering', 'Vercel Blog', 'https://vercel.com/atom'),
  ('aiengineering', 'The Verge AI', 'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml'),
  ('aiengineering', 'TechCrunch AI', 'https://techcrunch.com/category/artificial-intelligence/feed/'),
  ('aiengineering', 'VentureBeat AI', 'https://venturebeat.com/category/ai/feed/'),
  ('aiengineering', 'DeepMind Blog', 'https://deepmind.google/blog/rss.xml'),
  ('aiengineering', 'Together AI Blog', 'https://www.together.ai/blog/rss.xml'),
  ('aiengineering', 'Replicate Blog', 'https://replicate.com/blog/rss'),
  ('aiengineering', 'W&B Fully Connected', 'https://wandb.ai/fully-connected/rss.xml'),
  ('aiengineering', 'The Pragmatic Engineer', 'https://newsletter.pragmaticengineer.com/feed'),
  ('aiengineering', 'InfoQ AI/ML', 'https://feed.infoq.com/ai-ml-data-eng/'),
  ('aiengineering', 'MIT Tech Review AI', 'https://www.technologyreview.com/topic/artificial-intelligence/feed'),
  -- elon (20 feeds)
  ('elon', 'Google News Elon', 'https://news.google.com/rss/search?q=elon+musk&hl=en'),
  ('elon', 'TechCrunch', 'https://techcrunch.com/feed/'),
  ('elon', 'The Verge', 'https://www.theverge.com/rss/index.xml'),
  ('elon', 'Ars Technica', 'https://feeds.arstechnica.com/arstechnica/technology-lab'),
  ('elon', 'Wired', 'https://www.wired.com/feed/rss'),
  ('elon', 'Engadget', 'https://www.engadget.com/rss.xml'),
  ('elon', 'CNBC Tech', 'https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=19854910'),
  ('elon', 'Reuters Tech', 'https://www.reutersagency.com/feed/?taxonomy=best-topics&post_type=best'),
  ('elon', 'Bloomberg Tech', 'https://feeds.bloomberg.com/technology/news.rss'),
  ('elon', 'Electrek', 'https://electrek.co/feed/'),
  ('elon', 'Teslarati', 'https://www.teslarati.com/feed/'),
  ('elon', 'InsideEVs', 'https://insideevs.com/rss/make/tesla/'),
  ('elon', 'SpaceNews', 'https://spacenews.com/feed/'),
  ('elon', 'NASASpaceflight', 'https://www.nasaspaceflight.com/feed/'),
  ('elon', 'The Guardian Tech', 'https://www.theguardian.com/technology/rss'),
  ('elon', 'Business Insider Tech', 'https://www.businessinsider.com/tech?IR=T&format=rss'),
  ('elon', 'Forbes Innovation', 'https://www.forbes.com/innovation/feed/'),
  ('elon', 'Futurism', 'https://futurism.com/feed'),
  ('elon', 'VentureBeat', 'https://venturebeat.com/feed/'),
  ('elon', 'ZDNET', 'https://www.zdnet.com/news/rss.xml')
ON CONFLICT (topic_id, url) DO NOTHING;
