-- Migration 005: Create changelog table for update logs
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS changelog (
  id          serial PRIMARY KEY,
  version     text NOT NULL,
  title_en    text NOT NULL,
  title_fr    text NOT NULL,
  body_en     text NOT NULL DEFAULT '',
  body_fr     text NOT NULL DEFAULT '',
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS changelog_version_idx ON changelog (created_at DESC);

-- Seed: 1.86 → 1.49 one row per release; **1.0–1.48** = single aggregate row (same copy for all). Newest first. Re-running may duplicate rows unless you TRUNCATE changelog first.
-- Existing DB missing latest? Run `migrations/insert-changelog-1.86.sql` (or older insert-*.sql) in Supabase SQL Editor (once per version).
INSERT INTO changelog (version, title_en, title_fr, body_en, body_fr, created_at) VALUES
  ('1.86', 'v1.86: Cron rollback + member submission UX hardening', 'v1.86 : Retour réglage cron + solidification UX soumission membre', 'Restored previous cron runtime tuning (13s baseline) in fetch/score functions and removed 30s production overrides from netlify.toml for stability. Improved member topic-submission UX: after non-owner creation, show a message-only pending-validation view with a dedicated back-to-home action (no form shown). Refined home personalization controls so the top-analysis button stays globally available but is hidden during authenticated topic-edit mode.', 'Rétablissement du paramétrage cron précédent (baseline 13s) dans les fonctions fetch/score et suppression des overrides production 30s dans netlify.toml pour plus de stabilité. Amélioration UX de soumission de topic côté membre : après création non-owner, affichage d''un écran message-only de validation en attente avec action dédiée de retour à l''accueil (sans formulaire). Ajustement des contrôles de personnalisation home : le bouton d''analyse top reste globalement disponible mais est masqué pendant le mode édition des topics pour un utilisateur connecté.', '2026-04-12T22:00:00Z'),
  ('1.85', 'v1.85: On-demand top analysis, member topic submission and cache stability', 'v1.85 : Analyse top à la demande, soumission de topic membre et stabilité cache', 'Homepage top articles analysis is now user-triggered via a dedicated button ("Analyze top articles"), with contextual toasts for topic/period guidance and updated wording ("selected and analyzed by AI"). Signed-in members can propose new topics from home personalization; created topics are stored inactive/hidden pending owner validation, with a 24h max validation notice. Improved action-button visual consistency and hardened top-summary cache hit stability (deterministic ordering + normalized cache key).', 'L''analyse des top articles sur l''accueil devient déclenchée à la demande via un bouton dédié (« Analyse des top articles »), avec toasts de guidance topic/période et wording mis à jour (« sélectionnés et analysés par IA »). Les membres connectés peuvent proposer un nouveau topic depuis la personnalisation home ; les topics créés sont enregistrés inactifs/masqués en attente de validation owner, avec message de validation sous 24h max. Amélioration de la cohérence visuelle des boutons d''action et fiabilisation du cache de résumé top (ordre déterministe + clé normalisée).', '2026-04-12T20:00:00Z'),
  ('1.84', 'v1.84: Personalization UX + cron 30s budget + summary/count polish', 'v1.84 : Personnalisation topics + budget cron 30s + polish résumé', 'Added signed-in user topic personalization (selection, onboarding modal, per-user persistence, and homepage top-feed filtering by selected topics). Upgraded Netlify cron runtime budgeting to align with 30s server window (fetch + score budgets and production env defaults). Refined summary metadata wording for selected-topic mode (shows analyzed count) and polished the “Customize my topics” controls.', 'Ajout de la personnalisation des topics pour les utilisateurs connectés (sélection, onboarding, persistance par utilisateur et filtrage du flux top de l''accueil selon les topics choisis). Passage des budgets de runtime cron Netlify au nouveau plafond serveur 30s (fetch + score + variables de prod). Ajustement du libellé méta du résumé en mode topic sélectionné (affichage du nombre analysé) et amélioration UI des contrôles « Personnaliser mes topics ».', '2026-04-12T12:00:00Z'),
  ('1.83', 'v1.83: Top 50 homepage + AI grouped summary + display filtering', 'v1.83 : Top 50 accueil + résumé IA groupé + filtre affichage', 'Homepage Top feed now uses 50 articles over 24h. Topics include a new is_displayed toggle; hidden topics stay active for ingestion/scoring but are excluded from homepage display and Top feed selection. Added POST /api/news/top-summary for homepage AI summary with grouped bullet points and source references, plus audio playback in the same SummaryBox experience. UI updates include AI Summary label, Top 50 subtitle styling, progressive reveal animation for homepage summary, and loading indicator text.', 'Le flux Top de l''accueil passe à 50 articles sur 24h. Les topics ont un nouveau toggle is_displayed ; les topics masqués restent actifs pour l''ingestion/scoring mais sont exclus de l''affichage accueil et de la sélection Top. Ajout de POST /api/news/top-summary pour un résumé IA de la home avec bullet points groupés et références sources, avec lecture audio dans la même expérience SummaryBox. Mises à jour UI : libellé Résumé IA, style du sous-titre Top 50, animation d''affichage progressive du résumé sur la home et texte de chargement.', '2026-04-11T12:00:00Z'),
  ('1.82', 'v1.82: My Account, Users management, Top 20 timestamp, GA & AI labels', 'v1.82 : Mon compte, gestion utilisateurs, timestamp Top 20, GA & labels IA', 'Settings: My Account section for authenticated users (editable first/last name, read-only email and user type badge). Users management for owner users (inline edit name and type via service-role API). Homepage: removed manual refresh button; added last-updated timestamp on Top 20 subtitle (HH:MM). Baselines updated: EN "Tech intelligence, powered by AI." / FR "La tech décodée par l''IA". Topic creation reorganized: Label EN, Label FR, Slug on one row; Domain moved up; new "Generate with AI" button fills slug, label FR and domain from label EN via /api/topics/generate-labels. Cron status: score age only flags slow/high when backlog > 0. Google Analytics (G-X8RR3FMCR0) integrated in layout.tsx.', 'Paramètres : section Mon compte pour les utilisateurs connectés (prénom/nom modifiables, e-mail et type en lecture seule). Gestion des utilisateurs pour les owners (modification inline nom et type via API service-role). Accueil : bouton refresh supprimé ; horodatage de mise à jour sur le sous-titre Top 20 (HH:MM). Baselines mises à jour : EN « Tech intelligence, powered by AI. » / FR « La tech décodée par l''IA ». Création de topic réorganisée : Label EN, Label FR, Slug sur une ligne ; Domain remonté ; bouton « Generate with AI » remplit slug, label FR et domain depuis le label EN via /api/topics/generate-labels. Statut cron : l''âge du scoring ne déclenche slow/high que si le backlog > 0. Google Analytics (G-X8RR3FMCR0) intégré dans layout.tsx.', '2026-04-10T12:00:00Z'),
  ('1.81', 'v1.81: Member vs owner roles for admin screens', 'v1.81 : rôles member et owner pour les écrans admin', 'user_type in Supabase user_metadata: member (default at sign-up) or owner. Only owner can open Topics and Feed management; members stay on the same public areas as guests. Admin APIs use requireOwnerSession(): 401 if not signed in, 403 if member. Promote to owner in Supabase Dashboard → Authentication → Users → User metadata (user_type = owner); user must sign in again to refresh the JWT. src/lib/user-type.ts.', 'user_type dans les métadonnées utilisateur Supabase : member (défaut à l''inscription) ou owner. Seul owner accède à Topics et à la gestion des flux ; les members gardent les mêmes zones publiques que les invités. Les API admin utilisent requireOwnerSession() : 401 si non connecté, 403 si member. Passer en owner dans le dashboard Supabase → Authentication → Users → métadonnées (user_type = owner) ; nouvelle connexion pour rafraîchir le JWT. Fichier src/lib/user-type.ts.', '2026-04-16T12:00:00Z'),
  ('1.80', 'v1.80: Supabase sign-in for Topics & Feed management', 'v1.80 : connexion Supabase pour Topics et gestion des flux', 'Optional Supabase Auth (email + password). Guests keep full access to home, stats, crons, changelog, and settings. Topics and Feed management (nav icons + APIs) require a session; APIs return 401 without valid cookies. @supabase/ssr, middleware.ts session refresh, AuthProvider + AuthModal; registration stores first/last name in user_metadata. GET /api/topics without ?all=1 stays public for the homepage topic grid.', 'Authentification Supabase optionnelle (e-mail + mot de passe). Les invités gardent l''accès complet à l''accueil, stats, crons, changelog et paramètres. Les pages Topics et gestion des flux (icônes + API) exigent une session ; les API répondent 401 sans cookies valides. @supabase/ssr, middleware pour les cookies, AuthProvider + AuthModal ; inscription avec prénom/nom en user_metadata. GET /api/topics sans ?all=1 reste public pour la grille des sujets.', '2026-04-08T12:00:00Z'),
  ('1.79', 'Netlify 13s cron optimization & freshness SLA', 'Optimisation cron Netlify 13s & SLA fraîcheur', 'Cron-fetch and cron-score now enforce a strict Netlify-safe runtime budget (13s wall cap, internal budget plus safety reserve), with fresh-first scoring priority, adaptive per-run quotas, and anti-starvation fairness. Manual feed scoring route is now maxDuration 13 with elapsed-budget partial responses. Cron Monitor adds delay p95, SLA under 5m, fresh backlog 5m, and alerts.', 'cron-fetch et cron-score appliquent désormais un budget d''exécution strict compatible Netlify (cap 13s, budget interne + réserve), avec priorité de scoring fresh-first, quotas adaptatifs, et garde-fou anti-famine. La route de scoring manuel des flux passe en maxDuration 13 avec réponses partielles quand le budget est atteint. Cron Monitor ajoute délai p95, SLA < 5 min, backlog frais 5 min et alertes.', '2026-04-13T12:00:00Z'),
  ('1.78', 'Scoring backlog fix & Netlify-safe manual feed score', 'Scoring : backlog sans fenêtre 7j & flux admin Netlify', 'cron-score and post-fetch mini-score pass windowHours null: all unscored articles eligible (not only pub_date in last 168h). Backlog counts all unscored per topic. POST feeds/[feedId]/score: OpenAI batches of 12 in parallel, 8s timeout per call, maxDuration 26, trimmed source. test-score still defaults to 168h. version.json and APP_VERSION 1.78.', 'cron-score et mini-score post-fetch : windowHours null, tous les non scorés éligibles (plus seulement 168h de pub_date). Backlog = tous les non scorés par topic. Score manuel par flux : lots 12 en parallèle, timeout OpenAI 8s, maxDuration 26, source trim. test-score garde 168h par défaut. version 1.78.', '2026-04-12T12:00:00Z'),
  ('1.77', 'Release 1.77: version bump & .gitignore .claude', 'Version 1.77 : bump et gitignore .claude', 'public/version.json and APP_VERSION 1.77. .gitignore ignores .claude/ (local agent worktrees). SPEC §17 through 1.77; add this row to changelog table for in-app Changelog. No product change vs 1.76.', 'version.json et APP_VERSION 1.77. .gitignore exclut .claude/ (worktrees agents locaux). SPEC §17 jusqu''à 1.77 ; ajouter cette ligne dans changelog pour le journal in-app. Pas de changement produit par rapport à 1.76.', '2026-04-11T12:00:00Z'),
  ('1.76', 'Top 20 i18n, SPEC & changelog sync', 'Top 20 bilingue, SPEC et journal', 'Top 20: GET /api/news/top?lang=en|fr; localized snippet from snippet_ai_* or RSS; useTopFeed({ poll, lang }) refetches on language change; French UI shows AI summary as primary line when present. SPEC.md §6/§17 updated; migration seed rows 1.74–1.76; public/version.json and APP_VERSION 1.76.', 'Top 20 : /api/news/top?lang=, extrait localisé (snippet_ai_* ou RSS), useTopFeed({ poll, lang }) avec rechargement au changement de langue ; en français le résumé IA en titre principal si disponible. SPEC §6/§17 ; seed 005 ; version 1.76 (version.json, APP_VERSION).', '2026-04-10T12:00:00Z'),
  ('1.75', 'Feed scoring & home UI refactor', 'Scoring flux et refonte accueil', 'Manual POST .../feeds/[feedId]/score selects all unscored articles for that feed (newest first), max 50 per request—no 90-day pub_date window. UI refactor: AppHeader, TopFeedSection, useTopFeed({ poll }) hook; TopicsPage/ (List, Create, Detail); theme sectionCard + form styles; home strings in i18n. Top 20 lists RSS titles only (localized snippets added in v1.76).', 'Score manuel par flux : tous les articles non scorés (plus récents d''abord), max 50 par requête, sans fenêtre 90 jours sur pub_date. Refonte UI : AppHeader, TopFeedSection, hook useTopFeed({ poll }) ; TopicsPage/ ; theme sectionCard et formulaires ; textes d''accueil en i18n. Top 20 : titres RSS seuls (extraits localisés en v1.76).', '2026-04-09T12:00:00Z'),
  ('1.74', 'Housekeeping: CSS stack, shared libs, types', 'Nettoyage : CSS, libs partagées, types', 'Removed Tailwind and postcss.config; deleted obsolete root spec-*.md files. Canonical RSS fetch and scoring live in src/lib/fetch-topic-dynamic.ts and score-topic-dynamic.ts (Netlify functions/shared re-exports). globals.css for tables, grids, keyframes; theme.ts adds spinnerStyle, ghostBtn, ghostOutlineBtn; new cookies.ts. TopicLabel, ChangelogEntry, and FeedAdminRow moved to types.ts.', 'Suppression de Tailwind et postcss.config ; suppression des fichiers spec-*.md obsolètes à la racine. Fetch RSS et scoring dans src/lib/fetch-topic-dynamic.ts et score-topic-dynamic.ts (réexport dans netlify/functions/shared). globals.css (tableaux, grilles, keyframes) ; theme.ts (spinnerStyle, ghostBtn, ghostOutlineBtn) ; cookies.ts. TopicLabel, ChangelogEntry et FeedAdminRow déplacés vers types.ts.', '2026-04-08T12:00:00Z'),
  ('1.73', 'Feed management, changelog UI, UX polish', 'Gestion des flux, journal des mises à jour, polish UX', 'changelog table + GET /api/changelog + Changelog page. Feed management: GET /api/feeds-admin, score/delete actions, toasts. Layout 916px; EN/FR below icons; feed ranking title tooltip; fetch-feeds sets fetched_at. Feed table: Articles + Coverage columns; manual score up to 50 articles; 90-day window for unscored selection (superseded in v1.75 by all-time unscored pool).', 'Table changelog + page journal. Gestion des flux : feeds-admin, actions score/suppression, toasts. Largeur 916px ; EN/FR sous icônes ; title sur source dans stats ; fetched_at sur fetch-feeds. Table flux : colonnes Articles et couverture ; score manuel jusqu''à 50 articles ; fenêtre 90 jours pour le choix des articles (remplacée en v1.75 par tous les non scorés).', '2026-04-07T12:00:00Z'),
  ('1.72', 'Stats redesign & fetch delay fix', 'Refonte stats & correction délai fetch', 'Stats 3-state flow, kpi_only, article ranking lazy 50. Cron Monitor avg delay: scored_at − fetched_at as Xm XXs; fetched_at on inserts.', 'Stats 3 états, kpi_only, classement articles par 50. Délai moyen Cron : scored_at − fetched_at en Xm XXs ; fetched_at à l’insertion.', '2026-04-06T12:00:00Z'),
  ('1.71', 'Cron optimization phase 2', 'Optimisation cron phase 2', 'cron-fetch ~10 min cycle, adaptive mini-score, 6s reserve. cron-score multi-topic 12s deadline, threshold 20. fetchAndStoreTopicDynamic returns inserted count.', 'cron-fetch cycle ~10 min, mini-score adaptatif. cron-score multi-topic deadline 12s, seuil 20. Retour {summary, inserted} après fetch.', '2026-04-05T12:00:00Z'),
  ('1.70', 'Avg delay fix & doc sync', 'Correction délai moyen & sync doc', 'Cron Monitor avg delay cohort: pub_date 24h + scored only. SPEC sync.', 'Cohorte délai moyen : pub_date 24h + scorés. Sync SPEC.', '2026-04-04T12:00:00Z'),
  ('1.69', 'Cron optimization phase 1', 'Optimisation cron phase 1', 'Minute batched fetch k=min(ceil(N/15),3), ~12s deadline. cron-score backlog priority, post-fetch mini-score ≤15.', 'Fetch minute k=min(ceil(N/15),3), deadline ~12s. cron-score priorité backlog, mini-score post-fetch ≤15.', '2026-04-03T12:00:00Z'),
  ('1.68', 'Supabase pagination fix & Top 20 refresh', 'Pagination Supabase & refresh Top 20', '/api/cron-stats 1000-row pagination. Top 20 auto-refresh 5 min. Topic badge on Top 20.', '/api/cron-stats pagination 1000 lignes. Top 20 refresh 5 min. Badge topic.', '2026-04-02T12:00:00Z'),
  ('1.67', 'Summary metadata line (mobile)', 'Ligne méta résumé (mobile)', 'Compact summary stats line; mobile typography ≤640px.', 'Ligne compacte articles/scorés/analysés IA ; typo mobile ≤640px.', '2026-04-01T12:00:00Z'),
  ('1.66', 'Version bump & SPEC tree', 'Bump version & arbre SPEC', 'SPEC project tree folder name 8news/.', 'Arborescence SPEC corrigée (8news/).', '2026-03-31T12:00:00Z'),
  ('1.65', 'Copy link, Cron Reason, NEW badge', 'Copie lien, raison Cron, badge NEW', 'Copy-to-clipboard on cards; Cron statusReason column; NEW badge <1h on Top 20.', 'Copie lien ; colonne raison Cron ; badge NEW <1h sur Top 20.', '2026-03-30T12:00:00Z'),
  ('1.64', 'Topic clears Top 20', 'Topic vide le Top 20', 'Selecting topic clears Top 20; prompt to pick period.', 'Choix topic masque Top 20 ; invite à choisir une période.', '2026-03-29T12:00:00Z'),
  ('1.63', 'Home icon & Summary title', 'Icône accueil & titre résumé', 'Home + logo reset Top 20; topic name in Summary title; removed standalone Top 20 button.', 'Accueil + logo réinitialisent Top 20 ; nom du topic dans le titre résumé ; bouton Top 20 retiré.', '2026-03-28T12:00:00Z'),
  ('1.62', 'Score ≥ 7 label, Top 20 default, scroll top', 'Libellé Score ≥ 7, Top 20 par défaut', 'Rename Hit % to Score ≥ 7; feeds (7d); Top 24h default feed; scroll-to-top button.', 'Hit % → Score ≥ 7 ; flux (7j) ; Top 20 par défaut 24h ; bouton retour haut.', '2026-03-27T12:00:00Z'),
  ('1.61', 'Cron Monitor & All Articles', 'Cron Monitor & onglet Tous les articles', 'Cron Monitor page; All Articles by score; maxArticles up to 100; lazy All tab; article stats in Summary; local TZ timeline.', 'Page Cron Monitor ; onglet Tous trié par score ; maxArticles 100 ; lazy load ; stats dans résumé ; fuseau local timeline.', '2026-03-26T12:00:00Z'),
  ('1.60', 'Cron scoring batch & timeout', 'Batch scoring cron & timeout', '50 articles/batch, backlog skip, OpenAI timeout handling.', 'Lots de 50 articles, skip backlog, timeout OpenAI.', '2026-03-25T12:00:00Z'),
  ('1.59', 'Discover feeds for existing topics', 'Découverte de flux pour topics existants', 'Discover feeds by AI in topic edit view.', 'Bouton découverte de flux IA dans l’édition topic.', '2026-03-24T12:00:00Z'),
  ('1.58', 'Topics loading & reorder', 'Chargement topics & réordonnancement', 'Spinner while topics load; active/inactive toggle; drag & drop reorder.', 'Spinner topics ; actif/inactif ; glisser-déposer ordre.', '2026-03-23T12:00:00Z'),
  ('1.57', 'Stats periods & banner', 'Périodes stats & bannière', 'Update banner top-right; stats 1h/3h/6h/today; logo → home.', 'Bannière mise à jour en haut à droite ; stats 1h/3h/6h/aujourd’hui ; logo → accueil.', '2026-03-22T12:00:00Z'),
  ('1.56', 'Cron round-robin fix', 'Correction round-robin cron', 'Timestamps before processing; ≤100 score/run; score every minute.', 'Horodatage avant traitement ; ≤100 score/run ; score chaque minute.', '2026-03-21T12:00:00Z'),
  ('1.55', 'AI scoring tiers & feed discovery', 'Tiers scoring IA & découverte flux', 'Generate scoring with AI; auto RSS discovery on topic create; refresh topics on home return.', 'Génération critères IA ; découverte RSS à la création ; refresh topics au retour accueil.', '2026-03-20T12:00:00Z'),
  ('1.54', 'Compact KPIs & Anthropic topic', 'KPI compacts & topic Anthropic', '7 KPIs one line; Anthropic topic + 20 feeds.', '7 KPIs une ligne ; topic Anthropic + 20 flux.', '2026-03-19T12:00:00Z'),
  ('1.53', 'Prompts in DB, hardcoded cleanup', 'Prompts en base, nettoyage dur', 'Dynamic prompts from DB; removed prompts.ts, rss-feeds.ts, scoring-prompts.ts.', 'Prompts dynamiques Supabase ; suppression données en dur.', '2026-03-18T12:00:00Z'),
  ('1.52', 'Dynamic topics & crons', 'Topics dynamiques & crons', 'Topics/feeds from DB; TopicsPage; round-robin crons; removed 18 hardcoded crons.', 'Topics/flux en base ; TopicsPage ; crons round-robin ; suppression 18 crons figés.', '2026-03-17T12:00:00Z'),
  ('1.51', 'Scoring throughput & KPI filter', 'Débit scoring & filtre KPI', 'Boost scoring throughput; fix KPI period filter.', 'Montée en débit scoring ; correctif filtre période KPI.', '2026-03-16T12:00:00Z'),
  ('1.50', 'Update banner & stats periods', 'Bannière maj & périodes stats', 'Replace auto-reload with banner; stats yesterday, 3d, 7d, 30d.', 'Bannière au lieu du reload auto ; stats hier, 3j, 7j, 30j.', '2026-03-15T12:00:00Z'),
  ('1.49', 'Full Stats dashboard', 'Tableau de bord Stats complet', 'KPIs, score distribution, feed ranking, top articles, topic comparison.', 'KPIs, distribution scores, classement flux, top articles, comparaison topics.', '2026-03-14T12:00:00Z'),
  ('1.0–1.48', 'Early development (1.0–1.48)', 'Développement initial (1.0–1.48)', 'Earlier 8news.ai development before detailed changelog (see git history). Versions 1.49+ summarized in SPEC.md (section 17).', 'Développement 8news.ai antérieur au journal détaillé (voir historique git). Versions ≥1.49 résumées dans SPEC.md (section 17).', '2026-03-13T12:00:00Z')
;
